runtime: python27
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: model
  version: latest
- name: jinja2
  version: latest
